trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'mi-suscripcion'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group miGrupoDeRecursos --template-file iac/prod/main.bicep --parameters @iac/prod/parameters.prod.json
s